# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditGrid = QtWidgets.QLineEdit(Dialog)
        self.lineEditGrid.setObjectName("lineEditGrid")
        self.gridLayout.addWidget(self.lineEditGrid, 3, 2, 1, 1)
        self.lineEdit_dt = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dt.setObjectName("lineEdit_dt")
        self.gridLayout.addWidget(self.lineEdit_dt, 1, 2, 1, 1)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 6, 6, 1, 4)
        self.lineEdit_h = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.gridLayout.addWidget(self.lineEdit_h, 0, 2, 1, 1)
        self.lineEdit_K = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_K.setObjectName("lineEdit_K")
        self.gridLayout.addWidget(self.lineEdit_K, 4, 2, 1, 1)
        self.btnClearInput = QtWidgets.QPushButton(Dialog)
        self.btnClearInput.setObjectName("btnClearInput")
        self.gridLayout.addWidget(self.btnClearInput, 6, 2, 1, 2)
        self.label_K = QtWidgets.QLabel(Dialog)
        self.label_K.setObjectName("label_K")
        self.gridLayout.addWidget(self.label_K, 4, 0, 1, 2)
        self.lineEditPhi = QtWidgets.QLineEdit(Dialog)
        self.lineEditPhi.setEnabled(True)
        self.lineEditPhi.setObjectName("lineEditPhi")
        self.gridLayout.addWidget(self.lineEditPhi, 5, 2, 1, 1)
        self.lineEditX = QtWidgets.QLineEdit(Dialog)
        self.lineEditX.setObjectName("lineEditX")
        self.gridLayout.addWidget(self.lineEditX, 2, 2, 1, 1)
        self.lineEditY = QtWidgets.QLineEdit(Dialog)
        self.lineEditY.setObjectName("lineEditY")
        self.gridLayout.addWidget(self.lineEditY, 2, 7, 1, 2)
        self.labelY = QtWidgets.QLabel(Dialog)
        self.labelY.setObjectName("labelY")
        self.gridLayout.addWidget(self.labelY, 2, 5, 1, 1)
        self.labelGrid = QtWidgets.QLabel(Dialog)
        self.labelGrid.setObjectName("labelGrid")
        self.gridLayout.addWidget(self.labelGrid, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 9, 1, 1)
        self.label_h = QtWidgets.QLabel(Dialog)
        self.label_h.setObjectName("label_h")
        self.gridLayout.addWidget(self.label_h, 0, 0, 1, 2)
        self.labelX = QtWidgets.QLabel(Dialog)
        self.labelX.setObjectName("labelX")
        self.gridLayout.addWidget(self.labelX, 2, 0, 1, 2)
        self.label_dt = QtWidgets.QLabel(Dialog)
        self.label_dt.setObjectName("label_dt")
        self.gridLayout.addWidget(self.label_dt, 1, 0, 1, 2)
        self.labePhi = QtWidgets.QLabel(Dialog)
        self.labePhi.setObjectName("labePhi")
        self.gridLayout.addWidget(self.labePhi, 5, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 10, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_h, self.lineEdit_dt)
        Dialog.setTabOrder(self.lineEdit_dt, self.lineEditX)
        Dialog.setTabOrder(self.lineEditX, self.lineEditY)
        Dialog.setTabOrder(self.lineEditY, self.lineEditGrid)
        Dialog.setTabOrder(self.lineEditGrid, self.lineEdit_K)
        Dialog.setTabOrder(self.lineEdit_K, self.lineEditPhi)
        Dialog.setTabOrder(self.lineEditPhi, self.btnSave)
        Dialog.setTabOrder(self.btnSave, self.btnClearInput)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Detector"))
        self.lineEditGrid.setText(_translate("Dialog", "10"))
        self.lineEdit_dt.setText(_translate("Dialog", "20"))
        self.btnSave.setText(_translate("Dialog", "Save"))
        self.lineEdit_h.setText(_translate("Dialog", "10"))
        self.lineEdit_K.setText(_translate("Dialog", "0.1"))
        self.btnClearInput.setText(_translate("Dialog", "Clear Input"))
        self.label_K.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">K []</p></body></html>"))
        self.lineEditPhi.setText(_translate("Dialog", "18"))
        self.lineEditX.setText(_translate("Dialog", "50"))
        self.lineEditY.setText(_translate("Dialog", "50"))
        self.labelY.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Y [m]:</p></body></html>"))
        self.labelGrid.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">grid []:</p></body></html>"))
        self.label_h.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">h [m]:</p></body></html>"))
        self.labelX.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">X [m]:</p></body></html>"))
        self.label_dt.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">dt [s]:</p></body></html>"))
        self.labePhi.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">phi [rad]:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
