# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 283)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditAmin = QtWidgets.QLineEdit(Dialog)
        self.lineEditAmin.setObjectName("lineEditAmin")
        self.gridLayout.addWidget(self.lineEditAmin, 0, 3, 1, 1)
        self.labelAmin = QtWidgets.QLabel(Dialog)
        self.labelAmin.setObjectName("labelAmin")
        self.gridLayout.addWidget(self.labelAmin, 0, 2, 1, 1)
        self.label_r0min = QtWidgets.QLabel(Dialog)
        self.label_r0min.setObjectName("label_r0min")
        self.gridLayout.addWidget(self.label_r0min, 2, 2, 1, 1)
        self.lineEdit_r0min = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_r0min.setObjectName("lineEdit_r0min")
        self.gridLayout.addWidget(self.lineEdit_r0min, 2, 3, 1, 1)
        self.lineEditAmax = QtWidgets.QLineEdit(Dialog)
        self.lineEditAmax.setObjectName("lineEditAmax")
        self.gridLayout.addWidget(self.lineEditAmax, 2, 1, 1, 1)
        self.labelAmax = QtWidgets.QLabel(Dialog)
        self.labelAmax.setObjectName("labelAmax")
        self.gridLayout.addWidget(self.labelAmax, 2, 0, 1, 1)
        self.lineEditAb = QtWidgets.QLineEdit(Dialog)
        self.lineEditAb.setObjectName("lineEditAb")
        self.gridLayout.addWidget(self.lineEditAb, 0, 1, 1, 1)
        self.labelAb = QtWidgets.QLabel(Dialog)
        self.labelAb.setObjectName("labelAb")
        self.gridLayout.addWidget(self.labelAb, 0, 0, 1, 1)
        self.label_r0max = QtWidgets.QLabel(Dialog)
        self.label_r0max.setObjectName("label_r0max")
        self.gridLayout.addWidget(self.label_r0max, 3, 0, 1, 1)
        self.lineEdit_r0max = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_r0max.setObjectName("lineEdit_r0max")
        self.gridLayout.addWidget(self.lineEdit_r0max, 3, 1, 1, 1)
        self.labelF = QtWidgets.QLabel(Dialog)
        self.labelF.setObjectName("labelF")
        self.gridLayout.addWidget(self.labelF, 3, 2, 1, 1)
        self.lineEditF = QtWidgets.QLineEdit(Dialog)
        self.lineEditF.setObjectName("lineEditF")
        self.gridLayout.addWidget(self.lineEditF, 3, 3, 1, 1)
        self.btnClearInput = QtWidgets.QPushButton(Dialog)
        self.btnClearInput.setObjectName("btnClearInput")
        self.gridLayout.addWidget(self.btnClearInput, 5, 0, 1, 2)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 5, 2, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditAb, self.lineEditAmax)
        Dialog.setTabOrder(self.lineEditAmax, self.btnSave)
        Dialog.setTabOrder(self.btnSave, self.btnClearInput)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Radiation"))
        self.lineEditAmin.setText(_translate("Dialog", "1000"))
        self.labelAmin.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">A<span style=\" vertical-align:sub;\">min</span> [Bq]:</p></body></html>"))
        self.label_r0min.setText(_translate("Dialog", "<html><head/><body><p>r<span style=\" vertical-align:sub;\">0min</span> [m]</p></body></html>"))
        self.lineEdit_r0min.setText(_translate("Dialog", "10"))
        self.lineEditAmax.setText(_translate("Dialog", "1500"))
        self.labelAmax.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">A<span style=\" vertical-align:sub;\">max</span> [Bq]:</p></body></html>"))
        self.lineEditAb.setText(_translate("Dialog", "100"))
        self.labelAb.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">A<span style=\" vertical-align:sub;\">b</span> [Bq]:</p></body></html>"))
        self.label_r0max.setText(_translate("Dialog", "<html><head/><body><p>r<span style=\" vertical-align:sub;\">0max</span> [m]</p></body></html>"))
        self.lineEdit_r0max.setText(_translate("Dialog", "100"))
        self.labelF.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">F [mSv]:</p></body></html>"))
        self.lineEditF.setText(_translate("Dialog", "0.140"))
        self.btnClearInput.setText(_translate("Dialog", "Clear Input"))
        self.btnSave.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
