# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tutorial03.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 130, 200, 25))
        self.lineEdit.setObjectName("lineEdit")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(340, 170, 200, 121))
        self.textEdit.setObjectName("textEdit")

        self.button_lineEdit = QtWidgets.QPushButton(self.centralwidget)
        self.button_lineEdit.setGeometry(QtCore.QRect(600, 130, 112, 34))
        self.button_lineEdit.setObjectName("button_lineEdit")

        self.button_textEdit = QtWidgets.QPushButton(self.centralwidget)
        self.button_textEdit.setGeometry(QtCore.QRect(600, 210, 112, 34))
        self.button_textEdit.setObjectName("button_textEdit")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.button_lineEdit.clicked.connect(self.show_line())
        self.button_textEdit.clicked.connect(self.show_text())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def show_line(self):
        print(self.lineEdit.text())

    def show_text(self):
        print(self.lineEdit.toPlainText())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_lineEdit.setText(_translate("MainWindow", "Line edit"))
        self.button_textEdit.setText(_translate("MainWindow", "Text edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
