# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'describtion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.textDescrib = QtWidgets.QPlainTextEdit(Dialog)
        self.textDescrib.setObjectName("textDescrib")
        self.gridLayout.addWidget(self.textDescrib, 0, 0, 1, 1)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setObjectName("btnOK")
        self.gridLayout.addWidget(self.btnOK, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textDescrib.setPlainText(_translate("Dialog", "The application works when the A_b <= 1 Bq and A0 <= 1e5 Bq.\n"
"\n"
"Example of laboratory measurement with h = 0.1m and x_max = y_max = 1 m. It works."))
        self.btnOK.setText(_translate("Dialog", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
