# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogPars.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 208)
        Dialog.setMinimumSize(QtCore.QSize(501, 208))
        Dialog.setMaximumSize(QtCore.QSize(501, 208))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_h = QtWidgets.QLabel(Dialog)
        self.label_h.setObjectName("label_h")
        self.gridLayout.addWidget(self.label_h, 0, 0, 1, 1)
        self.lineEdit_h = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.gridLayout.addWidget(self.lineEdit_h, 0, 1, 1, 1)
        self.label_X = QtWidgets.QLabel(Dialog)
        self.label_X.setObjectName("label_X")
        self.gridLayout.addWidget(self.label_X, 1, 0, 1, 1)
        self.lineEdit_X = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.gridLayout.addWidget(self.lineEdit_X, 1, 1, 1, 1)
        self.label_Y = QtWidgets.QLabel(Dialog)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout.addWidget(self.label_Y, 1, 2, 1, 1)
        self.lineEdit_Y = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.gridLayout.addWidget(self.lineEdit_Y, 1, 3, 1, 2)
        self.label_m = QtWidgets.QLabel(Dialog)
        self.label_m.setObjectName("label_m")
        self.gridLayout.addWidget(self.label_m, 2, 0, 1, 1)
        self.lineEdit_m = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_m.setObjectName("lineEdit_m")
        self.gridLayout.addWidget(self.lineEdit_m, 2, 1, 1, 1)
        self.btnClear = QtWidgets.QPushButton(Dialog)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 3, 2, 1, 2)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 3, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parameters"))
        self.label_h.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">h [m]:</p></body></html>"))
        self.lineEdit_h.setText(_translate("Dialog", "10"))
        self.label_X.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">X [m]:</p></body></html>"))
        self.lineEdit_X.setText(_translate("Dialog", "50"))
        self.label_Y.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Y [m]:</p></body></html>"))
        self.lineEdit_Y.setText(_translate("Dialog", "50"))
        self.label_m.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">m []:</p></body></html>"))
        self.lineEdit_m.setText(_translate("Dialog", "16"))
        self.btnClear.setText(_translate("Dialog", "Clear"))
        self.btnSave.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
